2020-09-14 10:24:19,298 - INFO - Watching for file changes with StatReloader
2020-09-14 10:24:24,944 - INFO - 用户获取稿件信息
2020-09-14 10:24:30,349 - DEBUG - Using selector: SelectSelector
2020-09-14 10:24:30,436 - DEBUG - Using selector: SelectSelector
2020-09-14 10:37:25,554 - INFO - Watching for file changes with StatReloader
2020-09-14 10:37:26,826 - DEBUG - Using selector: SelectSelector
2020-09-14 10:37:26,913 - DEBUG - Using selector: SelectSelector
2020-09-14 10:37:53,503 - INFO - Watching for file changes with StatReloader
2020-09-14 10:37:54,877 - INFO - 用户稿件上传
2020-09-14 10:38:40,773 - ERROR - Internal Server Error: /manuscript/document
Traceback (most recent call last):
  File "D:\application\python37\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\application\python37\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\application\python37\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\application\python37\lib\site-packages\django\views\generic\base.py", line 73, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\application\python37\lib\site-packages\rest_framework\views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "D:\application\python37\lib\site-packages\rest_framework\views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\application\python37\lib\site-packages\rest_framework\views.py", line 476, in raise_uncaught_exception
    raise exc
  File "D:\application\python37\lib\site-packages\rest_framework\views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\pythonCode\whutNewsManage\manuscript\views.py", line 335, in get
    manuscriptFile=open(manuscript.memeory,'rb')
AttributeError: 'ManuscriptModel' object has no attribute 'memeory'
2020-09-14 10:39:13,843 - INFO - D:\pythonCode\whutNewsManage\manuscript\views.py changed, reloading.
2020-09-14 10:39:13,843 - DEBUG - Using selector: SelectSelector
2020-09-14 10:39:15,602 - INFO - Watching for file changes with StatReloader
2020-09-14 10:39:16,328 - ERROR - Internal Server Error: /manuscript/document
Traceback (most recent call last):
  File "D:\application\python37\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\application\python37\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\application\python37\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\application\python37\lib\site-packages\django\views\generic\base.py", line 73, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\application\python37\lib\site-packages\rest_framework\views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "D:\application\python37\lib\site-packages\rest_framework\views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\application\python37\lib\site-packages\rest_framework\views.py", line 476, in raise_uncaught_exception
    raise exc
  File "D:\application\python37\lib\site-packages\rest_framework\views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\pythonCode\whutNewsManage\manuscript\views.py", line 335, in get
    manuscriptFile=open(manuscript.memeory_way,'rb')
AttributeError: 'ManuscriptModel' object has no attribute 'memeory_way'
2020-09-14 10:39:29,243 - INFO - D:\pythonCode\whutNewsManage\manuscript\views.py changed, reloading.
2020-09-14 10:39:29,244 - DEBUG - Using selector: SelectSelector
2020-09-14 10:39:30,850 - INFO - Watching for file changes with StatReloader
2020-09-14 10:41:34,508 - INFO - D:\pythonCode\whutNewsManage\manuscript\views.py changed, reloading.
2020-09-14 10:41:34,508 - DEBUG - Using selector: SelectSelector
2020-09-14 10:41:35,893 - INFO - Watching for file changes with StatReloader
2020-09-14 10:43:23,458 - INFO - D:\pythonCode\whutNewsManage\manuscript\views.py changed, reloading.
2020-09-14 10:43:23,460 - DEBUG - Using selector: SelectSelector
2020-09-14 10:43:24,829 - INFO - Watching for file changes with StatReloader
2020-09-14 10:44:41,917 - INFO - D:\pythonCode\whutNewsManage\manuscript\views.py changed, reloading.
2020-09-14 10:44:41,918 - DEBUG - Using selector: SelectSelector
2020-09-14 10:44:43,192 - INFO - Watching for file changes with StatReloader
2020-09-14 10:47:03,890 - INFO - D:\pythonCode\whutNewsManage\manuscript\views.py changed, reloading.
2020-09-14 10:47:03,890 - DEBUG - Using selector: SelectSelector
2020-09-14 10:47:05,446 - INFO - Watching for file changes with StatReloader
2020-09-14 10:47:51,464 - ERROR - Internal Server Error: /manuscript/document
Traceback (most recent call last):
  File "D:\application\python37\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\application\python37\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\application\python37\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\application\python37\lib\site-packages\django\views\generic\base.py", line 73, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\application\python37\lib\site-packages\rest_framework\views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "D:\application\python37\lib\site-packages\rest_framework\views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\application\python37\lib\site-packages\rest_framework\views.py", line 476, in raise_uncaught_exception
    raise exc
  File "D:\application\python37\lib\site-packages\rest_framework\views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\pythonCode\whutNewsManage\manuscript\views.py", line 343, in get
    downloadFileThread.join()
  File "D:\application\python37\lib\threading.py", line 1039, in join
    raise RuntimeError("cannot join thread before it is started")
RuntimeError: cannot join thread before it is started
2020-09-14 10:48:06,219 - INFO - D:\pythonCode\whutNewsManage\manuscript\views.py changed, reloading.
2020-09-14 10:48:06,219 - DEBUG - Using selector: SelectSelector
2020-09-14 10:48:07,683 - INFO - Watching for file changes with StatReloader
2020-09-14 10:48:08,352 - ERROR - Internal Server Error: /manuscript/document
Traceback (most recent call last):
  File "D:\application\python37\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\application\python37\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\application\python37\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\application\python37\lib\site-packages\django\views\generic\base.py", line 73, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\application\python37\lib\site-packages\rest_framework\views.py", line 507, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "D:\application\python37\lib\site-packages\rest_framework\views.py", line 422, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
2020-09-14 10:48:37,661 - INFO - D:\pythonCode\whutNewsManage\manuscript\views.py changed, reloading.
2020-09-14 10:48:37,665 - DEBUG - Using selector: SelectSelector
2020-09-14 10:48:39,340 - INFO - Watching for file changes with StatReloader
2020-09-14 10:53:32,314 - INFO - D:\pythonCode\whutNewsManage\manuscript\views.py changed, reloading.
2020-09-14 10:53:32,316 - DEBUG - Using selector: SelectSelector
2020-09-14 10:53:34,566 - INFO - Watching for file changes with StatReloader
2020-09-14 10:53:35,780 - ERROR - Internal Server Error: /manuscript/document
Traceback (most recent call last):
  File "D:\application\python37\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\application\python37\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\application\python37\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\application\python37\lib\site-packages\django\views\generic\base.py", line 73, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\application\python37\lib\site-packages\rest_framework\views.py", line 507, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "D:\application\python37\lib\site-packages\rest_framework\views.py", line 422, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
2020-09-14 10:54:40,870 - INFO - D:\pythonCode\whutNewsManage\manuscript\views.py changed, reloading.
2020-09-14 10:54:40,870 - DEBUG - Using selector: SelectSelector
2020-09-14 10:54:42,643 - INFO - Watching for file changes with StatReloader
2020-09-14 10:56:08,381 - INFO - D:\pythonCode\whutNewsManage\manuscript\views.py changed, reloading.
2020-09-14 10:56:08,381 - DEBUG - Using selector: SelectSelector
2020-09-14 10:56:09,645 - INFO - Watching for file changes with StatReloader
2020-09-14 11:02:59,301 - INFO - D:\pythonCode\whutNewsManage\manuscript\views.py changed, reloading.
2020-09-14 11:02:59,301 - DEBUG - Using selector: SelectSelector
2020-09-14 11:03:00,797 - INFO - Watching for file changes with StatReloader
2020-09-14 11:05:43,664 - INFO - D:\pythonCode\whutNewsManage\manuscript\views.py changed, reloading.
2020-09-14 11:05:43,665 - DEBUG - Using selector: SelectSelector
2020-09-14 11:05:45,878 - INFO - Watching for file changes with StatReloader
2020-09-14 11:13:14,249 - INFO - D:\pythonCode\whutNewsManage\manuscript\views.py changed, reloading.
2020-09-14 11:13:14,250 - DEBUG - Using selector: SelectSelector
2020-09-14 11:13:15,727 - INFO - Watching for file changes with StatReloader
2020-09-14 11:14:05,965 - INFO - D:\pythonCode\whutNewsManage\manuscript\views.py changed, reloading.
2020-09-14 11:14:05,966 - DEBUG - Using selector: SelectSelector
2020-09-14 11:14:07,421 - INFO - Watching for file changes with StatReloader
2020-09-14 11:14:39,336 - INFO - D:\pythonCode\whutNewsManage\manuscript\views.py changed, reloading.
2020-09-14 11:14:39,337 - DEBUG - Using selector: SelectSelector
2020-09-14 11:14:40,813 - INFO - Watching for file changes with StatReloader
2020-09-14 11:23:20,164 - INFO - D:\pythonCode\whutNewsManage\manuscript\views.py changed, reloading.
2020-09-14 11:23:20,165 - DEBUG - Using selector: SelectSelector
2020-09-14 11:23:22,092 - INFO - Watching for file changes with StatReloader
2020-09-14 11:23:56,556 - DEBUG - Using selector: SelectSelector
2020-09-14 11:23:56,658 - DEBUG - Using selector: SelectSelector
2020-09-14 22:37:32,171 - INFO - Watching for file changes with StatReloader
2020-09-14 22:38:35,050 - WARNING - Unauthorized: /manuscript/check
2020-09-14 22:39:29,926 - DEBUG - Using selector: SelectSelector
2020-09-14 22:39:30,006 - DEBUG - Using selector: SelectSelector
2020-09-14 22:39:36,728 - INFO - Watching for file changes with StatReloader
2020-09-14 22:41:26,336 - DEBUG - Using selector: SelectSelector
2020-09-14 22:41:26,453 - DEBUG - Using selector: SelectSelector
2020-09-14 22:41:32,111 - INFO - Watching for file changes with StatReloader
2020-09-14 22:43:15,045 - INFO - D:\pythonCode\whutNewsManage\manuscript\views.py changed, reloading.
2020-09-14 22:43:15,046 - DEBUG - Using selector: SelectSelector
2020-09-14 22:43:17,111 - INFO - Watching for file changes with StatReloader
2020-09-14 22:45:55,800 - INFO - D:\pythonCode\whutNewsManage\manuscript\views.py changed, reloading.
2020-09-14 22:45:55,803 - DEBUG - Using selector: SelectSelector
2020-09-14 22:45:58,080 - INFO - Watching for file changes with StatReloader
2020-09-14 22:55:01,532 - INFO - D:\pythonCode\whutNewsManage\manuscript\views.py changed, reloading.
2020-09-14 22:55:01,536 - DEBUG - Using selector: SelectSelector
2020-09-14 22:55:03,995 - INFO - Watching for file changes with StatReloader
2020-09-14 22:55:43,863 - ERROR - Internal Server Error: /manuscript/check
Traceback (most recent call last):
  File "D:\application\python37\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\application\python37\lib\site-packages\django\db\backends\sqlite3\base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: near "is": syntax error

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\application\python37\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\application\python37\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\application\python37\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\application\python37\lib\site-packages\django\views\generic\base.py", line 73, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\application\python37\lib\site-packages\rest_framework\views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "D:\application\python37\lib\site-packages\rest_framework\views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\application\python37\lib\site-packages\rest_framework\views.py", line 476, in raise_uncaught_exception
    raise exc
  File "D:\application\python37\lib\site-packages\rest_framework\views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\pythonCode\whutNewsManage\manuscript\views.py", line 434, in get
    page=pageNumberPagination.paginate_queryset(queryset=allCheckManuscriptRecord,request=request,view=self)
  File "D:\application\python37\lib\site-packages\rest_framework\pagination.py", line 206, in paginate_queryset
    self.page = paginator.page(page_number)
  File "D:\application\python37\lib\site-packages\django\core\paginator.py", line 73, in page
    number = self.validate_number(number)
  File "D:\application\python37\lib\site-packages\django\core\paginator.py", line 51, in validate_number
    if number > self.num_pages:
  File "D:\application\python37\lib\site-packages\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "D:\application\python37\lib\site-packages\django\core\paginator.py", line 100, in num_pages
    if self.count == 0 and not self.allow_empty_first_page:
  File "D:\application\python37\lib\site-packages\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "D:\application\python37\lib\site-packages\django\core\paginator.py", line 94, in count
    return c()
  File "D:\application\python37\lib\site-packages\django\db\models\query.py", line 411, in count
    return self.query.get_count(using=self.db)
  File "D:\application\python37\lib\site-packages\django\db\models\sql\query.py", line 515, in get_count
    number = obj.get_aggregation(using, ['__count'])['__count']
  File "D:\application\python37\lib\site-packages\django\db\models\sql\query.py", line 500, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "D:\application\python37\lib\site-packages\django\db\models\sql\compiler.py", line 1154, in execute_sql
    cursor.execute(sql, params)
  File "D:\application\python37\lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
  File "D:\application\python37\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "D:\application\python37\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\application\python37\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\application\python37\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\application\python37\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\application\python37\lib\site-packages\django\db\backends\sqlite3\base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: near "is": syntax error
2020-09-14 22:55:47,882 - ERROR - Internal Server Error: /manuscript/check
Traceback (most recent call last):
  File "D:\application\python37\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\application\python37\lib\site-packages\django\db\backends\sqlite3\base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: near "is": syntax error

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\application\python37\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\application\python37\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\application\python37\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\application\python37\lib\site-packages\django\views\generic\base.py", line 73, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\application\python37\lib\site-packages\rest_framework\views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "D:\application\python37\lib\site-packages\rest_framework\views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\application\python37\lib\site-packages\rest_framework\views.py", line 476, in raise_uncaught_exception
    raise exc
  File "D:\application\python37\lib\site-packages\rest_framework\views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\pythonCode\whutNewsManage\manuscript\views.py", line 434, in get
    page=pageNumberPagination.paginate_queryset(queryset=allCheckManuscriptRecord,request=request,view=self)
  File "D:\application\python37\lib\site-packages\rest_framework\pagination.py", line 206, in paginate_queryset
    self.page = paginator.page(page_number)
  File "D:\application\python37\lib\site-packages\django\core\paginator.py", line 73, in page
    number = self.validate_number(number)
  File "D:\application\python37\lib\site-packages\django\core\paginator.py", line 51, in validate_number
    if number > self.num_pages:
  File "D:\application\python37\lib\site-packages\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "D:\application\python37\lib\site-packages\django\core\paginator.py", line 100, in num_pages
    if self.count == 0 and not self.allow_empty_first_page:
  File "D:\application\python37\lib\site-packages\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "D:\application\python37\lib\site-packages\django\core\paginator.py", line 94, in count
    return c()
  File "D:\application\python37\lib\site-packages\django\db\models\query.py", line 411, in count
    return self.query.get_count(using=self.db)
  File "D:\application\python37\lib\site-packages\django\db\models\sql\query.py", line 515, in get_count
    number = obj.get_aggregation(using, ['__count'])['__count']
  File "D:\application\python37\lib\site-packages\django\db\models\sql\query.py", line 500, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "D:\application\python37\lib\site-packages\django\db\models\sql\compiler.py", line 1154, in execute_sql
    cursor.execute(sql, params)
  File "D:\application\python37\lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
  File "D:\application\python37\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "D:\application\python37\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\application\python37\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\application\python37\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\application\python37\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\application\python37\lib\site-packages\django\db\backends\sqlite3\base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: near "is": syntax error
2020-09-14 22:55:54,927 - DEBUG - Using selector: SelectSelector
2020-09-14 22:55:55,032 - DEBUG - Using selector: SelectSelector
2020-09-14 22:55:58,780 - INFO - Watching for file changes with StatReloader
2020-09-14 22:56:01,686 - ERROR - Internal Server Error: /manuscript/check
Traceback (most recent call last):
  File "D:\application\python37\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\application\python37\lib\site-packages\django\db\backends\sqlite3\base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: near "is": syntax error

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\application\python37\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\application\python37\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\application\python37\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\application\python37\lib\site-packages\django\views\generic\base.py", line 73, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\application\python37\lib\site-packages\rest_framework\views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "D:\application\python37\lib\site-packages\rest_framework\views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\application\python37\lib\site-packages\rest_framework\views.py", line 476, in raise_uncaught_exception
    raise exc
  File "D:\application\python37\lib\site-packages\rest_framework\views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\pythonCode\whutNewsManage\manuscript\views.py", line 434, in get
    page=pageNumberPagination.paginate_queryset(queryset=allCheckManuscriptRecord,request=request,view=self)
  File "D:\application\python37\lib\site-packages\rest_framework\pagination.py", line 206, in paginate_queryset
    self.page = paginator.page(page_number)
  File "D:\application\python37\lib\site-packages\django\core\paginator.py", line 73, in page
    number = self.validate_number(number)
  File "D:\application\python37\lib\site-packages\django\core\paginator.py", line 51, in validate_number
    if number > self.num_pages:
  File "D:\application\python37\lib\site-packages\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "D:\application\python37\lib\site-packages\django\core\paginator.py", line 100, in num_pages
    if self.count == 0 and not self.allow_empty_first_page:
  File "D:\application\python37\lib\site-packages\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "D:\application\python37\lib\site-packages\django\core\paginator.py", line 94, in count
    return c()
  File "D:\application\python37\lib\site-packages\django\db\models\query.py", line 411, in count
    return self.query.get_count(using=self.db)
  File "D:\application\python37\lib\site-packages\django\db\models\sql\query.py", line 515, in get_count
    number = obj.get_aggregation(using, ['__count'])['__count']
  File "D:\application\python37\lib\site-packages\django\db\models\sql\query.py", line 500, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "D:\application\python37\lib\site-packages\django\db\models\sql\compiler.py", line 1154, in execute_sql
    cursor.execute(sql, params)
  File "D:\application\python37\lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
  File "D:\application\python37\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "D:\application\python37\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\application\python37\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\application\python37\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\application\python37\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\application\python37\lib\site-packages\django\db\backends\sqlite3\base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: near "is": syntax error
2020-09-14 22:57:13,621 - INFO - D:\pythonCode\whutNewsManage\manuscript\views.py changed, reloading.
2020-09-14 22:57:13,622 - DEBUG - Using selector: SelectSelector
2020-09-14 22:57:14,986 - INFO - Watching for file changes with StatReloader
2020-09-14 22:59:03,781 - INFO - D:\pythonCode\whutNewsManage\manuscript\views.py changed, reloading.
2020-09-14 22:59:03,782 - DEBUG - Using selector: SelectSelector
2020-09-14 22:59:05,630 - INFO - Watching for file changes with StatReloader
2020-09-14 23:01:27,131 - INFO - D:\pythonCode\whutNewsManage\manuscript\views.py changed, reloading.
2020-09-14 23:01:27,131 - DEBUG - Using selector: SelectSelector
2020-09-14 23:01:28,556 - INFO - Watching for file changes with StatReloader
2020-09-14 23:02:19,859 - DEBUG - Using selector: SelectSelector
2020-09-14 23:02:19,974 - DEBUG - Using selector: SelectSelector
